# Generated by Django 5.2.4 on 2025-08-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains & Bread'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('leftovers', 'Leftovers'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Catalog items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('container_type', models.CharField(choices=[('FRIDGE', 'Fridge'), ('FREEZER', 'Freezer'), ('PANTRY', 'Pantry'), ('SHOPPING', 'Shopping List')], default='FRIDGE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of this food item in the container')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Expiration date for this food item in the container', null=True)),
                ('checked_off', models.BooleanField(default=False, help_text='Whether item is checked off (e.g., in shopping list)')),
                ('is_frozen', models.BooleanField(default=False, help_text='Check if the item is frozen')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_entries', to='main_app.catalogitem')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main_app.container')),
            ],
            options={
                'verbose_name_plural': 'Container items',
                'ordering': ['expiration_date', 'catalog_item__name'],
                'unique_together': {('container', 'catalog_item')},
            },
        ),
    ]
