# Generated by Django 5.2.4 on 2025-08-02 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containerfood',
            options={'ordering': ['expiration_date', 'catalog_food__name'], 'verbose_name_plural': 'Container Food Items'},
        ),
        migrations.CreateModel(
            name='CatalogFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat & Poultry'), ('seafood', 'Seafood'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains & Bread'), ('condiments', 'Condiments & Sauces'), ('beverages', 'Beverages'), ('leftovers', 'Leftovers'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Catalog items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='containerfood',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='containerfood',
            name='catalog_food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='container_entries', to='main_app.catalogfood'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='containerfood',
            unique_together={('container', 'catalog_food')},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, help_text="User's birthday (month and day only)", null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='containerfood',
            name='catalog_item',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
    ]
